namespace :solidus_indonesia do
  desc "Loads Indonesia seed data."
  task load_seeds: :environment do
    puts "Remove Countries except Indonesia"
    Spree::Country.where.not(name: "Indonesia").delete_all
    puts "Remove All States"
    Spree::State.delete_all
    puts "Loading seed file: States and Cities (Indonesia)"
    country = Spree::Country.find_by_name('Indonesia')
    Spree::State.find_or_create_by(id: 1, name: 'Aceh', country_id: country.id)
    Spree::City.find_or_create_by(id: 1, name: 'Kabupaten Simeulue', state_id: '1')
    Spree::City.find_or_create_by(id: 2, name: 'Kabupaten Aceh Singkil', state_id: '1')
    Spree::City.find_or_create_by(id: 3, name: 'Kabupaten Aceh Selatan', state_id: '1')
    Spree::City.find_or_create_by(id: 4, name: 'Kabupaten Aceh Tenggara', state_id: '1')
    Spree::City.find_or_create_by(id: 5, name: 'Kabupaten Aceh Timur', state_id: '1')
    Spree::City.find_or_create_by(id: 6, name: 'Kabupaten Aceh Tengah', state_id: '1')
    Spree::City.find_or_create_by(id: 7, name: 'Kabupaten Aceh Barat', state_id: '1')
    Spree::City.find_or_create_by(id: 8, name: 'Kabupaten Aceh Besar', state_id: '1')
    Spree::City.find_or_create_by(id: 9, name: 'Kabupaten Pidie', state_id: '1')
    Spree::City.find_or_create_by(id: 10, name: 'Kabupaten Bireuen', state_id: '1')
    Spree::City.find_or_create_by(id: 11, name: 'Kabupaten Aceh Utara', state_id: '1')
    Spree::City.find_or_create_by(id: 12, name: 'Kabupaten Aceh Barat Daya', state_id: '1')
    Spree::City.find_or_create_by(id: 13, name: 'Kabupaten Gayo Lues', state_id: '1')
    Spree::City.find_or_create_by(id: 14, name: 'Kabupaten Aceh Tamiang', state_id: '1')
    Spree::City.find_or_create_by(id: 15, name: 'Kabupaten Nagan Raya', state_id: '1')
    Spree::City.find_or_create_by(id: 16, name: 'Kabupaten Aceh Jaya', state_id: '1')
    Spree::City.find_or_create_by(id: 17, name: 'Kabupaten Bener Meriah', state_id: '1')
    Spree::City.find_or_create_by(id: 18, name: 'Kabupaten Pidie Jaya', state_id: '1')
    Spree::City.find_or_create_by(id: 19, name: 'Kota Banda Aceh', state_id: '1')
    Spree::City.find_or_create_by(id: 20, name: 'Kota Sabang', state_id: '1')
    Spree::City.find_or_create_by(id: 21, name: 'Kota Langsa', state_id: '1')
    Spree::City.find_or_create_by(id: 22, name: 'Kota Lhokseumawe', state_id: '1')
    Spree::City.find_or_create_by(id: 23, name: 'Kota Subulussalam', state_id: '1')
    Spree::State.find_or_create_by(id: 2, name: 'Sumatera Utara', country_id: country.id)
    Spree::City.find_or_create_by(id: 24, name: 'Kabupaten Nias', state_id: '2')
    Spree::City.find_or_create_by(id: 25, name: 'Kabupaten Mandailing Natal', state_id: '2')
    Spree::City.find_or_create_by(id: 26, name: 'Kabupaten Tapanuli Selatan', state_id: '2')
    Spree::City.find_or_create_by(id: 27, name: 'Kabupaten Tapanuli Tengah', state_id: '2')
    Spree::City.find_or_create_by(id: 28, name: 'Kabupaten Tapanuli Utara', state_id: '2')
    Spree::City.find_or_create_by(id: 29, name: 'Kabupaten Toba Samosir', state_id: '2')
    Spree::City.find_or_create_by(id: 30, name: 'Kabupaten Labuhan Batu', state_id: '2')
    Spree::City.find_or_create_by(id: 31, name: 'Kabupaten Asahan', state_id: '2')
    Spree::City.find_or_create_by(id: 32, name: 'Kabupaten Simalungun', state_id: '2')
    Spree::City.find_or_create_by(id: 33, name: 'Kabupaten Dairi', state_id: '2')
    Spree::City.find_or_create_by(id: 34, name: 'Kabupaten Karo', state_id: '2')
    Spree::City.find_or_create_by(id: 35, name: 'Kabupaten Deli Serdang', state_id: '2')
    Spree::City.find_or_create_by(id: 36, name: 'Kabupaten Langkat', state_id: '2')
    Spree::City.find_or_create_by(id: 37, name: 'Kabupaten Nias Selatan', state_id: '2')
    Spree::City.find_or_create_by(id: 38, name: 'Kabupaten Humbang Hasundutan', state_id: '2')
    Spree::City.find_or_create_by(id: 39, name: 'Kabupaten Pakpak Bharat', state_id: '2')
    Spree::City.find_or_create_by(id: 40, name: 'Kabupaten Samosir', state_id: '2')
    Spree::City.find_or_create_by(id: 41, name: 'Kabupaten Serdang Bedagai', state_id: '2')
    Spree::City.find_or_create_by(id: 42, name: 'Kabupaten Batu Bara', state_id: '2')
    Spree::City.find_or_create_by(id: 43, name: 'Kabupaten Padang Lawas Utara', state_id: '2')
    Spree::City.find_or_create_by(id: 44, name: 'Kabupaten Padang Lawas', state_id: '2')
    Spree::City.find_or_create_by(id: 45, name: 'Kabupaten Labuhan Batu Selatan', state_id: '2')
    Spree::City.find_or_create_by(id: 46, name: 'Kabupaten Labuhan Batu Utara', state_id: '2')
    Spree::City.find_or_create_by(id: 47, name: 'Kabupaten Nias Utara', state_id: '2')
    Spree::City.find_or_create_by(id: 48, name: 'Kabupaten Nias Barat', state_id: '2')
    Spree::City.find_or_create_by(id: 49, name: 'Kota Sibolga', state_id: '2')
    Spree::City.find_or_create_by(id: 50, name: 'Kota Tanjung Balai', state_id: '2')
    Spree::City.find_or_create_by(id: 51, name: 'Kota Pematang Siantar', state_id: '2')
    Spree::City.find_or_create_by(id: 52, name: 'Kota Tebing Tinggi', state_id: '2')
    Spree::City.find_or_create_by(id: 53, name: 'Kota Medan', state_id: '2')
    Spree::City.find_or_create_by(id: 54, name: 'Kota Binjai', state_id: '2')
    Spree::City.find_or_create_by(id: 55, name: 'Kota Padangsidimpuan', state_id: '2')
    Spree::City.find_or_create_by(id: 56, name: 'Kota Gunungsitoli', state_id: '2')
    Spree::State.find_or_create_by(id: 3, name: 'Sumatera Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 57, name: 'Kabupaten Kepulauan Mentawai', state_id: '3')
    Spree::City.find_or_create_by(id: 58, name: 'Kabupaten Pesisir Selatan', state_id: '3')
    Spree::City.find_or_create_by(id: 59, name: 'Kabupaten Solok', state_id: '3')
    Spree::City.find_or_create_by(id: 60, name: 'Kabupaten Sijunjung', state_id: '3')
    Spree::City.find_or_create_by(id: 61, name: 'Kabupaten Tanah Datar', state_id: '3')
    Spree::City.find_or_create_by(id: 62, name: 'Kabupaten Padang Pariaman', state_id: '3')
    Spree::City.find_or_create_by(id: 63, name: 'Kabupaten Agam', state_id: '3')
    Spree::City.find_or_create_by(id: 64, name: 'Kabupaten Lima Puluh Kota', state_id: '3')
    Spree::City.find_or_create_by(id: 65, name: 'Kabupaten Pasaman', state_id: '3')
    Spree::City.find_or_create_by(id: 66, name: 'Kabupaten Solok Selatan', state_id: '3')
    Spree::City.find_or_create_by(id: 67, name: 'Kabupaten Dharmasraya', state_id: '3')
    Spree::City.find_or_create_by(id: 68, name: 'Kabupaten Pasaman Barat', state_id: '3')
    Spree::City.find_or_create_by(id: 69, name: 'Kota Padang', state_id: '3')
    Spree::City.find_or_create_by(id: 70, name: 'Kota Solok', state_id: '3')
    Spree::City.find_or_create_by(id: 71, name: 'Kota Sawah Lunto', state_id: '3')
    Spree::City.find_or_create_by(id: 72, name: 'Kota Padang Panjang', state_id: '3')
    Spree::City.find_or_create_by(id: 73, name: 'Kota Bukittinggi', state_id: '3')
    Spree::City.find_or_create_by(id: 74, name: 'Kota Payakumbuh', state_id: '3')
    Spree::City.find_or_create_by(id: 75, name: 'Kota Pariaman', state_id: '3')
    Spree::State.find_or_create_by(id: 4, name: 'Riau', country_id: country.id)
    Spree::City.find_or_create_by(id: 76, name: 'Kabupaten Kuantan Singingi', state_id: '4')
    Spree::City.find_or_create_by(id: 77, name: 'Kabupaten Indragiri Hulu', state_id: '4')
    Spree::City.find_or_create_by(id: 78, name: 'Kabupaten Indragiri Hilir', state_id: '4')
    Spree::City.find_or_create_by(id: 79, name: 'Kabupaten Pelalawan', state_id: '4')
    Spree::City.find_or_create_by(id: 80, name: 'Kabupaten S I A K', state_id: '4')
    Spree::City.find_or_create_by(id: 81, name: 'Kabupaten Kampar', state_id: '4')
    Spree::City.find_or_create_by(id: 82, name: 'Kabupaten Rokan Hulu', state_id: '4')
    Spree::City.find_or_create_by(id: 83, name: 'Kabupaten Bengkalis', state_id: '4')
    Spree::City.find_or_create_by(id: 84, name: 'Kabupaten Rokan Hilir', state_id: '4')
    Spree::City.find_or_create_by(id: 85, name: 'Kabupaten Kepulauan Meranti', state_id: '4')
    Spree::City.find_or_create_by(id: 86, name: 'Kota Pekanbaru', state_id: '4')
    Spree::City.find_or_create_by(id: 87, name: 'Kota D U M A I', state_id: '4')
    Spree::State.find_or_create_by(id: 5, name: 'Jambi', country_id: country.id)
    Spree::City.find_or_create_by(id: 88, name: 'Kabupaten Kerinci', state_id: '5')
    Spree::City.find_or_create_by(id: 89, name: 'Kabupaten Merangin', state_id: '5')
    Spree::City.find_or_create_by(id: 90, name: 'Kabupaten Sarolangun', state_id: '5')
    Spree::City.find_or_create_by(id: 91, name: 'Kabupaten Batang Hari', state_id: '5')
    Spree::City.find_or_create_by(id: 92, name: 'Kabupaten Muaro Jambi', state_id: '5')
    Spree::City.find_or_create_by(id: 93, name: 'Kabupaten Tanjung Jabung Timur', state_id: '5')
    Spree::City.find_or_create_by(id: 94, name: 'Kabupaten Tanjung Jabung Barat', state_id: '5')
    Spree::City.find_or_create_by(id: 95, name: 'Kabupaten Tebo', state_id: '5')
    Spree::City.find_or_create_by(id: 96, name: 'Kabupaten Bungo', state_id: '5')
    Spree::City.find_or_create_by(id: 97, name: 'Kota Jambi', state_id: '5')
    Spree::City.find_or_create_by(id: 98, name: 'Kota Sungai Penuh', state_id: '5')
    Spree::State.find_or_create_by(id: 6, name: 'Sumatera Selatan', country_id: country.id)
    Spree::City.find_or_create_by(id: 99, name: 'Kabupaten Ogan Komering Ulu', state_id: '6')
    Spree::City.find_or_create_by(id: 100, name: 'Kabupaten Ogan Komering Ilir', state_id: '6')
    Spree::City.find_or_create_by(id: 101, name: 'Kabupaten Muara Enim', state_id: '6')
    Spree::City.find_or_create_by(id: 102, name: 'Kabupaten Lahat', state_id: '6')
    Spree::City.find_or_create_by(id: 103, name: 'Kabupaten Musi Rawas', state_id: '6')
    Spree::City.find_or_create_by(id: 104, name: 'Kabupaten Musi Banyuasin', state_id: '6')
    Spree::City.find_or_create_by(id: 105, name: 'Kabupaten Banyu Asin', state_id: '6')
    Spree::City.find_or_create_by(id: 106, name: 'Kabupaten Ogan Komering Ulu Selatan', state_id: '6')
    Spree::City.find_or_create_by(id: 107, name: 'Kabupaten Ogan Komering Ulu Timur', state_id: '6')
    Spree::City.find_or_create_by(id: 108, name: 'Kabupaten Ogan Ilir', state_id: '6')
    Spree::City.find_or_create_by(id: 109, name: 'Kabupaten Empat Lawang', state_id: '6')
    Spree::City.find_or_create_by(id: 110, name: 'Kabupaten Penukal Abab Lematang Ilir', state_id: '6')
    Spree::City.find_or_create_by(id: 111, name: 'Kabupaten Musi Rawas Utara', state_id: '6')
    Spree::City.find_or_create_by(id: 112, name: 'Kota Palembang', state_id: '6')
    Spree::City.find_or_create_by(id: 113, name: 'Kota Prabumulih', state_id: '6')
    Spree::City.find_or_create_by(id: 114, name: 'Kota Pagar Alam', state_id: '6')
    Spree::City.find_or_create_by(id: 115, name: 'Kota Lubuklinggau', state_id: '6')
    Spree::State.find_or_create_by(id: 7, name: 'Bengkulu', country_id: country.id)
    Spree::City.find_or_create_by(id: 116, name: 'Kabupaten Bengkulu Selatan', state_id: '7')
    Spree::City.find_or_create_by(id: 117, name: 'Kabupaten Rejang Lebong', state_id: '7')
    Spree::City.find_or_create_by(id: 118, name: 'Kabupaten Bengkulu Utara', state_id: '7')
    Spree::City.find_or_create_by(id: 119, name: 'Kabupaten Kaur', state_id: '7')
    Spree::City.find_or_create_by(id: 120, name: 'Kabupaten Seluma', state_id: '7')
    Spree::City.find_or_create_by(id: 121, name: 'Kabupaten Mukomuko', state_id: '7')
    Spree::City.find_or_create_by(id: 122, name: 'Kabupaten Lebong', state_id: '7')
    Spree::City.find_or_create_by(id: 123, name: 'Kabupaten Kepahiang', state_id: '7')
    Spree::City.find_or_create_by(id: 124, name: 'Kabupaten Bengkulu Tengah', state_id: '7')
    Spree::City.find_or_create_by(id: 125, name: 'Kota Bengkulu', state_id: '7')
    Spree::State.find_or_create_by(id: 8, name: 'Lampung', country_id: country.id)
    Spree::City.find_or_create_by(id: 126, name: 'Kabupaten Lampung Barat', state_id: '8')
    Spree::City.find_or_create_by(id: 127, name: 'Kabupaten Tanggamus', state_id: '8')
    Spree::City.find_or_create_by(id: 128, name: 'Kabupaten Lampung Selatan', state_id: '8')
    Spree::City.find_or_create_by(id: 129, name: 'Kabupaten Lampung Timur', state_id: '8')
    Spree::City.find_or_create_by(id: 130, name: 'Kabupaten Lampung Tengah', state_id: '8')
    Spree::City.find_or_create_by(id: 131, name: 'Kabupaten Lampung Utara', state_id: '8')
    Spree::City.find_or_create_by(id: 132, name: 'Kabupaten Way Kanan', state_id: '8')
    Spree::City.find_or_create_by(id: 133, name: 'Kabupaten Tulangbawang', state_id: '8')
    Spree::City.find_or_create_by(id: 134, name: 'Kabupaten Pesawaran', state_id: '8')
    Spree::City.find_or_create_by(id: 135, name: 'Kabupaten Pringsewu', state_id: '8')
    Spree::City.find_or_create_by(id: 136, name: 'Kabupaten Mesuji', state_id: '8')
    Spree::City.find_or_create_by(id: 137, name: 'Kabupaten Tulang Bawang Barat', state_id: '8')
    Spree::City.find_or_create_by(id: 138, name: 'Kabupaten Pesisir Barat', state_id: '8')
    Spree::City.find_or_create_by(id: 139, name: 'Kota Bandar Lampung', state_id: '8')
    Spree::City.find_or_create_by(id: 140, name: 'Kota Metro', state_id: '8')
    Spree::State.find_or_create_by(id: 9, name: 'Kepulauan Bangka Belitung', country_id: country.id)
    Spree::City.find_or_create_by(id: 141, name: 'Kabupaten Bangka', state_id: '9')
    Spree::City.find_or_create_by(id: 142, name: 'Kabupaten Belitung', state_id: '9')
    Spree::City.find_or_create_by(id: 143, name: 'Kabupaten Bangka Barat', state_id: '9')
    Spree::City.find_or_create_by(id: 144, name: 'Kabupaten Bangka Tengah', state_id: '9')
    Spree::City.find_or_create_by(id: 145, name: 'Kabupaten Bangka Selatan', state_id: '9')
    Spree::City.find_or_create_by(id: 146, name: 'Kabupaten Belitung Timur', state_id: '9')
    Spree::City.find_or_create_by(id: 147, name: 'Kota Pangkal Pinang', state_id: '9')
    Spree::State.find_or_create_by(id: 10, name: 'Kepulauan Riau', country_id: country.id)
    Spree::City.find_or_create_by(id: 148, name: 'Kabupaten Karimun', state_id: '10')
    Spree::City.find_or_create_by(id: 149, name: 'Kabupaten Bintan', state_id: '10')
    Spree::City.find_or_create_by(id: 150, name: 'Kabupaten Natuna', state_id: '10')
    Spree::City.find_or_create_by(id: 151, name: 'Kabupaten Lingga', state_id: '10')
    Spree::City.find_or_create_by(id: 152, name: 'Kabupaten Kepulauan Anambas', state_id: '10')
    Spree::City.find_or_create_by(id: 153, name: 'Kota B A T A M', state_id: '10')
    Spree::City.find_or_create_by(id: 154, name: 'Kota Tanjung Pinang', state_id: '10')
    Spree::State.find_or_create_by(id: 11, name: 'Dki Jakarta', country_id: country.id)
    Spree::City.find_or_create_by(id: 155, name: 'Kabupaten Kepulauan Seribu', state_id: '11')
    Spree::City.find_or_create_by(id: 156, name: 'Kota Jakarta Selatan', state_id: '11')
    Spree::City.find_or_create_by(id: 157, name: 'Kota Jakarta Timur', state_id: '11')
    Spree::City.find_or_create_by(id: 158, name: 'Kota Jakarta Pusat', state_id: '11')
    Spree::City.find_or_create_by(id: 159, name: 'Kota Jakarta Barat', state_id: '11')
    Spree::City.find_or_create_by(id: 160, name: 'Kota Jakarta Utara', state_id: '11')
    Spree::State.find_or_create_by(id: 12, name: 'Jawa Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 161, name: 'Kabupaten Bogor', state_id: '12')
    Spree::City.find_or_create_by(id: 162, name: 'Kabupaten Sukabumi', state_id: '12')
    Spree::City.find_or_create_by(id: 163, name: 'Kabupaten Cianjur', state_id: '12')
    Spree::City.find_or_create_by(id: 164, name: 'Kabupaten Bandung', state_id: '12')
    Spree::City.find_or_create_by(id: 165, name: 'Kabupaten Garut', state_id: '12')
    Spree::City.find_or_create_by(id: 166, name: 'Kabupaten Tasikmalaya', state_id: '12')
    Spree::City.find_or_create_by(id: 167, name: 'Kabupaten Ciamis', state_id: '12')
    Spree::City.find_or_create_by(id: 168, name: 'Kabupaten Kuningan', state_id: '12')
    Spree::City.find_or_create_by(id: 169, name: 'Kabupaten Cirebon', state_id: '12')
    Spree::City.find_or_create_by(id: 170, name: 'Kabupaten Majalengka', state_id: '12')
    Spree::City.find_or_create_by(id: 171, name: 'Kabupaten Sumedang', state_id: '12')
    Spree::City.find_or_create_by(id: 172, name: 'Kabupaten Indramayu', state_id: '12')
    Spree::City.find_or_create_by(id: 173, name: 'Kabupaten Subang', state_id: '12')
    Spree::City.find_or_create_by(id: 174, name: 'Kabupaten Purwakarta', state_id: '12')
    Spree::City.find_or_create_by(id: 175, name: 'Kabupaten Karawang', state_id: '12')
    Spree::City.find_or_create_by(id: 176, name: 'Kabupaten Bekasi', state_id: '12')
    Spree::City.find_or_create_by(id: 177, name: 'Kabupaten Bandung Barat', state_id: '12')
    Spree::City.find_or_create_by(id: 178, name: 'Kabupaten Pangandaran', state_id: '12')
    Spree::City.find_or_create_by(id: 179, name: 'Kota Bogor', state_id: '12')
    Spree::City.find_or_create_by(id: 180, name: 'Kota Sukabumi', state_id: '12')
    Spree::City.find_or_create_by(id: 181, name: 'Kota Bandung', state_id: '12')
    Spree::City.find_or_create_by(id: 182, name: 'Kota Cirebon', state_id: '12')
    Spree::City.find_or_create_by(id: 183, name: 'Kota Bekasi', state_id: '12')
    Spree::City.find_or_create_by(id: 184, name: 'Kota Depok', state_id: '12')
    Spree::City.find_or_create_by(id: 185, name: 'Kota Cimahi', state_id: '12')
    Spree::City.find_or_create_by(id: 186, name: 'Kota Tasikmalaya', state_id: '12')
    Spree::City.find_or_create_by(id: 187, name: 'Kota Banjar', state_id: '12')
    Spree::State.find_or_create_by(id: 13, name: 'Jawa Tengah', country_id: country.id)
    Spree::City.find_or_create_by(id: 188, name: 'Kabupaten Cilacap', state_id: '13')
    Spree::City.find_or_create_by(id: 189, name: 'Kabupaten Banyumas', state_id: '13')
    Spree::City.find_or_create_by(id: 190, name: 'Kabupaten Purbalingga', state_id: '13')
    Spree::City.find_or_create_by(id: 191, name: 'Kabupaten Banjarnegara', state_id: '13')
    Spree::City.find_or_create_by(id: 192, name: 'Kabupaten Kebumen', state_id: '13')
    Spree::City.find_or_create_by(id: 193, name: 'Kabupaten Purworejo', state_id: '13')
    Spree::City.find_or_create_by(id: 194, name: 'Kabupaten Wonosobo', state_id: '13')
    Spree::City.find_or_create_by(id: 195, name: 'Kabupaten Magelang', state_id: '13')
    Spree::City.find_or_create_by(id: 196, name: 'Kabupaten Boyolali', state_id: '13')
    Spree::City.find_or_create_by(id: 197, name: 'Kabupaten Klaten', state_id: '13')
    Spree::City.find_or_create_by(id: 198, name: 'Kabupaten Sukoharjo', state_id: '13')
    Spree::City.find_or_create_by(id: 199, name: 'Kabupaten Wonogiri', state_id: '13')
    Spree::City.find_or_create_by(id: 200, name: 'Kabupaten Karanganyar', state_id: '13')
    Spree::City.find_or_create_by(id: 201, name: 'Kabupaten Sragen', state_id: '13')
    Spree::City.find_or_create_by(id: 202, name: 'Kabupaten Grobogan', state_id: '13')
    Spree::City.find_or_create_by(id: 203, name: 'Kabupaten Blora', state_id: '13')
    Spree::City.find_or_create_by(id: 204, name: 'Kabupaten Rembang', state_id: '13')
    Spree::City.find_or_create_by(id: 205, name: 'Kabupaten Pati', state_id: '13')
    Spree::City.find_or_create_by(id: 206, name: 'Kabupaten Kudus', state_id: '13')
    Spree::City.find_or_create_by(id: 207, name: 'Kabupaten Jepara', state_id: '13')
    Spree::City.find_or_create_by(id: 208, name: 'Kabupaten Demak', state_id: '13')
    Spree::City.find_or_create_by(id: 209, name: 'Kabupaten Semarang', state_id: '13')
    Spree::City.find_or_create_by(id: 210, name: 'Kabupaten Temanggung', state_id: '13')
    Spree::City.find_or_create_by(id: 211, name: 'Kabupaten Kendal', state_id: '13')
    Spree::City.find_or_create_by(id: 212, name: 'Kabupaten Batang', state_id: '13')
    Spree::City.find_or_create_by(id: 213, name: 'Kabupaten Pekalongan', state_id: '13')
    Spree::City.find_or_create_by(id: 214, name: 'Kabupaten Pemalang', state_id: '13')
    Spree::City.find_or_create_by(id: 215, name: 'Kabupaten Tegal', state_id: '13')
    Spree::City.find_or_create_by(id: 216, name: 'Kabupaten Brebes', state_id: '13')
    Spree::City.find_or_create_by(id: 217, name: 'Kota Magelang', state_id: '13')
    Spree::City.find_or_create_by(id: 218, name: 'Kota Surakarta', state_id: '13')
    Spree::City.find_or_create_by(id: 219, name: 'Kota Salatiga', state_id: '13')
    Spree::City.find_or_create_by(id: 220, name: 'Kota Semarang', state_id: '13')
    Spree::City.find_or_create_by(id: 221, name: 'Kota Pekalongan', state_id: '13')
    Spree::City.find_or_create_by(id: 222, name: 'Kota Tegal', state_id: '13')
    Spree::State.find_or_create_by(id: 14, name: 'Di Yogyakarta', country_id: country.id)
    Spree::City.find_or_create_by(id: 223, name: 'Kabupaten Kulon Progo', state_id: '14')
    Spree::City.find_or_create_by(id: 224, name: 'Kabupaten Bantul', state_id: '14')
    Spree::City.find_or_create_by(id: 225, name: 'Kabupaten Gunung Kidul', state_id: '14')
    Spree::City.find_or_create_by(id: 226, name: 'Kabupaten Sleman', state_id: '14')
    Spree::City.find_or_create_by(id: 227, name: 'Kota Yogyakarta', state_id: '14')
    Spree::State.find_or_create_by(id: 15, name: 'Jawa Timur', country_id: country.id)
    Spree::City.find_or_create_by(id: 228, name: 'Kabupaten Pacitan', state_id: '15')
    Spree::City.find_or_create_by(id: 229, name: 'Kabupaten Ponorogo', state_id: '15')
    Spree::City.find_or_create_by(id: 230, name: 'Kabupaten Trenggalek', state_id: '15')
    Spree::City.find_or_create_by(id: 231, name: 'Kabupaten Tulungagung', state_id: '15')
    Spree::City.find_or_create_by(id: 232, name: 'Kabupaten Blitar', state_id: '15')
    Spree::City.find_or_create_by(id: 233, name: 'Kabupaten Kediri', state_id: '15')
    Spree::City.find_or_create_by(id: 234, name: 'Kabupaten Malang', state_id: '15')
    Spree::City.find_or_create_by(id: 235, name: 'Kabupaten Lumajang', state_id: '15')
    Spree::City.find_or_create_by(id: 236, name: 'Kabupaten Jember', state_id: '15')
    Spree::City.find_or_create_by(id: 237, name: 'Kabupaten Banyuwangi', state_id: '15')
    Spree::City.find_or_create_by(id: 238, name: 'Kabupaten Bondowoso', state_id: '15')
    Spree::City.find_or_create_by(id: 239, name: 'Kabupaten Situbondo', state_id: '15')
    Spree::City.find_or_create_by(id: 240, name: 'Kabupaten Probolinggo', state_id: '15')
    Spree::City.find_or_create_by(id: 241, name: 'Kabupaten Pasuruan', state_id: '15')
    Spree::City.find_or_create_by(id: 242, name: 'Kabupaten Sidoarjo', state_id: '15')
    Spree::City.find_or_create_by(id: 243, name: 'Kabupaten Mojokerto', state_id: '15')
    Spree::City.find_or_create_by(id: 244, name: 'Kabupaten Jombang', state_id: '15')
    Spree::City.find_or_create_by(id: 245, name: 'Kabupaten Nganjuk', state_id: '15')
    Spree::City.find_or_create_by(id: 246, name: 'Kabupaten Madiun', state_id: '15')
    Spree::City.find_or_create_by(id: 247, name: 'Kabupaten Magetan', state_id: '15')
    Spree::City.find_or_create_by(id: 248, name: 'Kabupaten Ngawi', state_id: '15')
    Spree::City.find_or_create_by(id: 249, name: 'Kabupaten Bojonegoro', state_id: '15')
    Spree::City.find_or_create_by(id: 250, name: 'Kabupaten Tuban', state_id: '15')
    Spree::City.find_or_create_by(id: 251, name: 'Kabupaten Lamongan', state_id: '15')
    Spree::City.find_or_create_by(id: 252, name: 'Kabupaten Gresik', state_id: '15')
    Spree::City.find_or_create_by(id: 253, name: 'Kabupaten Bangkalan', state_id: '15')
    Spree::City.find_or_create_by(id: 254, name: 'Kabupaten Sampang', state_id: '15')
    Spree::City.find_or_create_by(id: 255, name: 'Kabupaten Pamekasan', state_id: '15')
    Spree::City.find_or_create_by(id: 256, name: 'Kabupaten Sumenep', state_id: '15')
    Spree::City.find_or_create_by(id: 257, name: 'Kota Kediri', state_id: '15')
    Spree::City.find_or_create_by(id: 258, name: 'Kota Blitar', state_id: '15')
    Spree::City.find_or_create_by(id: 259, name: 'Kota Malang', state_id: '15')
    Spree::City.find_or_create_by(id: 260, name: 'Kota Probolinggo', state_id: '15')
    Spree::City.find_or_create_by(id: 261, name: 'Kota Pasuruan', state_id: '15')
    Spree::City.find_or_create_by(id: 262, name: 'Kota Mojokerto', state_id: '15')
    Spree::City.find_or_create_by(id: 263, name: 'Kota Madiun', state_id: '15')
    Spree::City.find_or_create_by(id: 264, name: 'Kota Surabaya', state_id: '15')
    Spree::City.find_or_create_by(id: 265, name: 'Kota Batu', state_id: '15')
    Spree::State.find_or_create_by(id: 16, name: 'Banten', country_id: country.id)
    Spree::City.find_or_create_by(id: 266, name: 'Kabupaten Pandeglang', state_id: '16')
    Spree::City.find_or_create_by(id: 267, name: 'Kabupaten Lebak', state_id: '16')
    Spree::City.find_or_create_by(id: 268, name: 'Kabupaten Tangerang', state_id: '16')
    Spree::City.find_or_create_by(id: 269, name: 'Kabupaten Serang', state_id: '16')
    Spree::City.find_or_create_by(id: 270, name: 'Kota Tangerang', state_id: '16')
    Spree::City.find_or_create_by(id: 271, name: 'Kota Cilegon', state_id: '16')
    Spree::City.find_or_create_by(id: 272, name: 'Kota Serang', state_id: '16')
    Spree::City.find_or_create_by(id: 273, name: 'Kota Tangerang Selatan', state_id: '16')
    Spree::State.find_or_create_by(id: 17, name: 'Bali', country_id: country.id)
    Spree::City.find_or_create_by(id: 274, name: 'Kabupaten Jembrana', state_id: '17')
    Spree::City.find_or_create_by(id: 275, name: 'Kabupaten Tabanan', state_id: '17')
    Spree::City.find_or_create_by(id: 276, name: 'Kabupaten Badung', state_id: '17')
    Spree::City.find_or_create_by(id: 277, name: 'Kabupaten Gianyar', state_id: '17')
    Spree::City.find_or_create_by(id: 278, name: 'Kabupaten Klungkung', state_id: '17')
    Spree::City.find_or_create_by(id: 279, name: 'Kabupaten Bangli', state_id: '17')
    Spree::City.find_or_create_by(id: 280, name: 'Kabupaten Karang Asem', state_id: '17')
    Spree::City.find_or_create_by(id: 281, name: 'Kabupaten Buleleng', state_id: '17')
    Spree::City.find_or_create_by(id: 282, name: 'Kota Denpasar', state_id: '17')
    Spree::State.find_or_create_by(id: 18, name: 'Nusa Tenggara Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 283, name: 'Kabupaten Lombok Barat', state_id: '18')
    Spree::City.find_or_create_by(id: 284, name: 'Kabupaten Lombok Tengah', state_id: '18')
    Spree::City.find_or_create_by(id: 285, name: 'Kabupaten Lombok Timur', state_id: '18')
    Spree::City.find_or_create_by(id: 286, name: 'Kabupaten Sumbawa', state_id: '18')
    Spree::City.find_or_create_by(id: 287, name: 'Kabupaten Dompu', state_id: '18')
    Spree::City.find_or_create_by(id: 288, name: 'Kabupaten Bima', state_id: '18')
    Spree::City.find_or_create_by(id: 289, name: 'Kabupaten Sumbawa Barat', state_id: '18')
    Spree::City.find_or_create_by(id: 290, name: 'Kabupaten Lombok Utara', state_id: '18')
    Spree::City.find_or_create_by(id: 291, name: 'Kota Mataram', state_id: '18')
    Spree::City.find_or_create_by(id: 292, name: 'Kota Bima', state_id: '18')
    Spree::State.find_or_create_by(id: 19, name: 'Nusa Tenggara Timur', country_id: country.id)
    Spree::City.find_or_create_by(id: 293, name: 'Kabupaten Sumba Barat', state_id: '19')
    Spree::City.find_or_create_by(id: 294, name: 'Kabupaten Sumba Timur', state_id: '19')
    Spree::City.find_or_create_by(id: 295, name: 'Kabupaten Kupang', state_id: '19')
    Spree::City.find_or_create_by(id: 296, name: 'Kabupaten Timor Tengah Selatan', state_id: '19')
    Spree::City.find_or_create_by(id: 297, name: 'Kabupaten Timor Tengah Utara', state_id: '19')
    Spree::City.find_or_create_by(id: 298, name: 'Kabupaten Belu', state_id: '19')
    Spree::City.find_or_create_by(id: 299, name: 'Kabupaten Alor', state_id: '19')
    Spree::City.find_or_create_by(id: 300, name: 'Kabupaten Lembata', state_id: '19')
    Spree::City.find_or_create_by(id: 301, name: 'Kabupaten Flores Timur', state_id: '19')
    Spree::City.find_or_create_by(id: 302, name: 'Kabupaten Sikka', state_id: '19')
    Spree::City.find_or_create_by(id: 303, name: 'Kabupaten Ende', state_id: '19')
    Spree::City.find_or_create_by(id: 304, name: 'Kabupaten Ngada', state_id: '19')
    Spree::City.find_or_create_by(id: 305, name: 'Kabupaten Manggarai', state_id: '19')
    Spree::City.find_or_create_by(id: 306, name: 'Kabupaten Rote Ndao', state_id: '19')
    Spree::City.find_or_create_by(id: 307, name: 'Kabupaten Manggarai Barat', state_id: '19')
    Spree::City.find_or_create_by(id: 308, name: 'Kabupaten Sumba Tengah', state_id: '19')
    Spree::City.find_or_create_by(id: 309, name: 'Kabupaten Sumba Barat Daya', state_id: '19')
    Spree::City.find_or_create_by(id: 310, name: 'Kabupaten Nagekeo', state_id: '19')
    Spree::City.find_or_create_by(id: 311, name: 'Kabupaten Manggarai Timur', state_id: '19')
    Spree::City.find_or_create_by(id: 312, name: 'Kabupaten Sabu Raijua', state_id: '19')
    Spree::City.find_or_create_by(id: 313, name: 'Kabupaten Malaka', state_id: '19')
    Spree::City.find_or_create_by(id: 314, name: 'Kota Kupang', state_id: '19')
    Spree::State.find_or_create_by(id: 20, name: 'Kalimantan Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 315, name: 'Kabupaten Sambas', state_id: '20')
    Spree::City.find_or_create_by(id: 316, name: 'Kabupaten Bengkayang', state_id: '20')
    Spree::City.find_or_create_by(id: 317, name: 'Kabupaten Landak', state_id: '20')
    Spree::City.find_or_create_by(id: 318, name: 'Kabupaten Mempawah', state_id: '20')
    Spree::City.find_or_create_by(id: 319, name: 'Kabupaten Sanggau', state_id: '20')
    Spree::City.find_or_create_by(id: 320, name: 'Kabupaten Ketapang', state_id: '20')
    Spree::City.find_or_create_by(id: 321, name: 'Kabupaten Sintang', state_id: '20')
    Spree::City.find_or_create_by(id: 322, name: 'Kabupaten Kapuas Hulu', state_id: '20')
    Spree::City.find_or_create_by(id: 323, name: 'Kabupaten Sekadau', state_id: '20')
    Spree::City.find_or_create_by(id: 324, name: 'Kabupaten Melawi', state_id: '20')
    Spree::City.find_or_create_by(id: 325, name: 'Kabupaten Kayong Utara', state_id: '20')
    Spree::City.find_or_create_by(id: 326, name: 'Kabupaten Kubu Raya', state_id: '20')
    Spree::City.find_or_create_by(id: 327, name: 'Kota Pontianak', state_id: '20')
    Spree::City.find_or_create_by(id: 328, name: 'Kota Singkawang', state_id: '20')
    Spree::State.find_or_create_by(id: 21, name: 'Kalimantan Tengah', country_id: country.id)
    Spree::City.find_or_create_by(id: 329, name: 'Kabupaten Kotawaringin Barat', state_id: '21')
    Spree::City.find_or_create_by(id: 330, name: 'Kabupaten Kotawaringin Timur', state_id: '21')
    Spree::City.find_or_create_by(id: 331, name: 'Kabupaten Kapuas', state_id: '21')
    Spree::City.find_or_create_by(id: 332, name: 'Kabupaten Barito Selatan', state_id: '21')
    Spree::City.find_or_create_by(id: 333, name: 'Kabupaten Barito Utara', state_id: '21')
    Spree::City.find_or_create_by(id: 334, name: 'Kabupaten Sukamara', state_id: '21')
    Spree::City.find_or_create_by(id: 335, name: 'Kabupaten Lamandau', state_id: '21')
    Spree::City.find_or_create_by(id: 336, name: 'Kabupaten Seruyan', state_id: '21')
    Spree::City.find_or_create_by(id: 337, name: 'Kabupaten Katingan', state_id: '21')
    Spree::City.find_or_create_by(id: 338, name: 'Kabupaten Pulang Pisau', state_id: '21')
    Spree::City.find_or_create_by(id: 339, name: 'Kabupaten Gunung Mas', state_id: '21')
    Spree::City.find_or_create_by(id: 340, name: 'Kabupaten Barito Timur', state_id: '21')
    Spree::City.find_or_create_by(id: 341, name: 'Kabupaten Murung Raya', state_id: '21')
    Spree::City.find_or_create_by(id: 342, name: 'Kota Palangka Raya', state_id: '21')
    Spree::State.find_or_create_by(id: 22, name: 'Kalimantan Selatan', country_id: country.id)
    Spree::City.find_or_create_by(id: 343, name: 'Kabupaten Tanah Laut', state_id: '22')
    Spree::City.find_or_create_by(id: 344, name: 'Kabupaten Kota Baru', state_id: '22')
    Spree::City.find_or_create_by(id: 345, name: 'Kabupaten Banjar', state_id: '22')
    Spree::City.find_or_create_by(id: 346, name: 'Kabupaten Barito Kuala', state_id: '22')
    Spree::City.find_or_create_by(id: 347, name: 'Kabupaten Tapin', state_id: '22')
    Spree::City.find_or_create_by(id: 348, name: 'Kabupaten Hulu Sungai Selatan', state_id: '22')
    Spree::City.find_or_create_by(id: 349, name: 'Kabupaten Hulu Sungai Tengah', state_id: '22')
    Spree::City.find_or_create_by(id: 350, name: 'Kabupaten Hulu Sungai Utara', state_id: '22')
    Spree::City.find_or_create_by(id: 351, name: 'Kabupaten Tabalong', state_id: '22')
    Spree::City.find_or_create_by(id: 352, name: 'Kabupaten Tanah Bumbu', state_id: '22')
    Spree::City.find_or_create_by(id: 353, name: 'Kabupaten Balangan', state_id: '22')
    Spree::City.find_or_create_by(id: 354, name: 'Kota Banjarmasin', state_id: '22')
    Spree::City.find_or_create_by(id: 355, name: 'Kota Banjar Baru', state_id: '22')
    Spree::State.find_or_create_by(id: 23, name: 'Kalimantan Timur', country_id: country.id)
    Spree::City.find_or_create_by(id: 356, name: 'Kabupaten Paser', state_id: '23')
    Spree::City.find_or_create_by(id: 357, name: 'Kabupaten Kutai Barat', state_id: '23')
    Spree::City.find_or_create_by(id: 358, name: 'Kabupaten Kutai Kartanegara', state_id: '23')
    Spree::City.find_or_create_by(id: 359, name: 'Kabupaten Kutai Timur', state_id: '23')
    Spree::City.find_or_create_by(id: 360, name: 'Kabupaten Berau', state_id: '23')
    Spree::City.find_or_create_by(id: 361, name: 'Kabupaten Penajam Paser Utara', state_id: '23')
    Spree::City.find_or_create_by(id: 362, name: 'Kabupaten Mahakam Hulu', state_id: '23')
    Spree::City.find_or_create_by(id: 363, name: 'Kota Balikpapan', state_id: '23')
    Spree::City.find_or_create_by(id: 364, name: 'Kota Samarinda', state_id: '23')
    Spree::City.find_or_create_by(id: 365, name: 'Kota Bontang', state_id: '23')
    Spree::State.find_or_create_by(id: 24, name: 'Kalimantan Utara', country_id: country.id)
    Spree::City.find_or_create_by(id: 366, name: 'Kabupaten Malinau', state_id: '24')
    Spree::City.find_or_create_by(id: 367, name: 'Kabupaten Bulungan', state_id: '24')
    Spree::City.find_or_create_by(id: 368, name: 'Kabupaten Tana Tidung', state_id: '24')
    Spree::City.find_or_create_by(id: 369, name: 'Kabupaten Nunukan', state_id: '24')
    Spree::City.find_or_create_by(id: 370, name: 'Kota Tarakan', state_id: '24')
    Spree::State.find_or_create_by(id: 25, name: 'Sulawesi Utara', country_id: country.id)
    Spree::City.find_or_create_by(id: 371, name: 'Kabupaten Bolaang Mongondow', state_id: '25')
    Spree::City.find_or_create_by(id: 372, name: 'Kabupaten Minahasa', state_id: '25')
    Spree::City.find_or_create_by(id: 373, name: 'Kabupaten Kepulauan Sangihe', state_id: '25')
    Spree::City.find_or_create_by(id: 374, name: 'Kabupaten Kepulauan Talaud', state_id: '25')
    Spree::City.find_or_create_by(id: 375, name: 'Kabupaten Minahasa Selatan', state_id: '25')
    Spree::City.find_or_create_by(id: 376, name: 'Kabupaten Minahasa Utara', state_id: '25')
    Spree::City.find_or_create_by(id: 377, name: 'Kabupaten Bolaang Mongondow Utara', state_id: '25')
    Spree::City.find_or_create_by(id: 378, name: 'Kabupaten Siau Tagulandang Biaro', state_id: '25')
    Spree::City.find_or_create_by(id: 379, name: 'Kabupaten Minahasa Tenggara', state_id: '25')
    Spree::City.find_or_create_by(id: 380, name: 'Kabupaten Bolaang Mongondow Selatan', state_id: '25')
    Spree::City.find_or_create_by(id: 381, name: 'Kabupaten Bolaang Mongondow Timur', state_id: '25')
    Spree::City.find_or_create_by(id: 382, name: 'Kota Manado', state_id: '25')
    Spree::City.find_or_create_by(id: 383, name: 'Kota Bitung', state_id: '25')
    Spree::City.find_or_create_by(id: 384, name: 'Kota Tomohon', state_id: '25')
    Spree::City.find_or_create_by(id: 385, name: 'Kota Kotamobagu', state_id: '25')
    Spree::State.find_or_create_by(id: 26, name: 'Sulawesi Tengah', country_id: country.id)
    Spree::City.find_or_create_by(id: 386, name: 'Kabupaten Banggai Kepulauan', state_id: '26')
    Spree::City.find_or_create_by(id: 387, name: 'Kabupaten Banggai', state_id: '26')
    Spree::City.find_or_create_by(id: 388, name: 'Kabupaten Morowali', state_id: '26')
    Spree::City.find_or_create_by(id: 389, name: 'Kabupaten Poso', state_id: '26')
    Spree::City.find_or_create_by(id: 390, name: 'Kabupaten Donggala', state_id: '26')
    Spree::City.find_or_create_by(id: 391, name: 'Kabupaten Toli-toli', state_id: '26')
    Spree::City.find_or_create_by(id: 392, name: 'Kabupaten Buol', state_id: '26')
    Spree::City.find_or_create_by(id: 393, name: 'Kabupaten Parigi Moutong', state_id: '26')
    Spree::City.find_or_create_by(id: 394, name: 'Kabupaten Tojo Una-una', state_id: '26')
    Spree::City.find_or_create_by(id: 395, name: 'Kabupaten Sigi', state_id: '26')
    Spree::City.find_or_create_by(id: 396, name: 'Kabupaten Banggai Laut', state_id: '26')
    Spree::City.find_or_create_by(id: 397, name: 'Kabupaten Morowali Utara', state_id: '26')
    Spree::City.find_or_create_by(id: 398, name: 'Kota Palu', state_id: '26')
    Spree::State.find_or_create_by(id: 27, name: 'Sulawesi Selatan', country_id: country.id)
    Spree::City.find_or_create_by(id: 399, name: 'Kabupaten Kepulauan Selayar', state_id: '27')
    Spree::City.find_or_create_by(id: 400, name: 'Kabupaten Bulukumba', state_id: '27')
    Spree::City.find_or_create_by(id: 401, name: 'Kabupaten Bantaeng', state_id: '27')
    Spree::City.find_or_create_by(id: 402, name: 'Kabupaten Jeneponto', state_id: '27')
    Spree::City.find_or_create_by(id: 403, name: 'Kabupaten Takalar', state_id: '27')
    Spree::City.find_or_create_by(id: 404, name: 'Kabupaten Gowa', state_id: '27')
    Spree::City.find_or_create_by(id: 405, name: 'Kabupaten Sinjai', state_id: '27')
    Spree::City.find_or_create_by(id: 406, name: 'Kabupaten Maros', state_id: '27')
    Spree::City.find_or_create_by(id: 407, name: 'Kabupaten Pangkajene Dan Kepulauan', state_id: '27')
    Spree::City.find_or_create_by(id: 408, name: 'Kabupaten Barru', state_id: '27')
    Spree::City.find_or_create_by(id: 409, name: 'Kabupaten Bone', state_id: '27')
    Spree::City.find_or_create_by(id: 410, name: 'Kabupaten Soppeng', state_id: '27')
    Spree::City.find_or_create_by(id: 411, name: 'Kabupaten Wajo', state_id: '27')
    Spree::City.find_or_create_by(id: 412, name: 'Kabupaten Sidenreng Rappang', state_id: '27')
    Spree::City.find_or_create_by(id: 413, name: 'Kabupaten Pinrang', state_id: '27')
    Spree::City.find_or_create_by(id: 414, name: 'Kabupaten Enrekang', state_id: '27')
    Spree::City.find_or_create_by(id: 415, name: 'Kabupaten Luwu', state_id: '27')
    Spree::City.find_or_create_by(id: 416, name: 'Kabupaten Tana Toraja', state_id: '27')
    Spree::City.find_or_create_by(id: 417, name: 'Kabupaten Luwu Utara', state_id: '27')
    Spree::City.find_or_create_by(id: 418, name: 'Kabupaten Luwu Timur', state_id: '27')
    Spree::City.find_or_create_by(id: 419, name: 'Kabupaten Toraja Utara', state_id: '27')
    Spree::City.find_or_create_by(id: 420, name: 'Kota Makassar', state_id: '27')
    Spree::City.find_or_create_by(id: 421, name: 'Kota Parepare', state_id: '27')
    Spree::City.find_or_create_by(id: 422, name: 'Kota Palopo', state_id: '27')
    Spree::State.find_or_create_by(id: 28, name: 'Sulawesi Tenggara', country_id: country.id)
    Spree::City.find_or_create_by(id: 423, name: 'Kabupaten Buton', state_id: '28')
    Spree::City.find_or_create_by(id: 424, name: 'Kabupaten Muna', state_id: '28')
    Spree::City.find_or_create_by(id: 425, name: 'Kabupaten Konawe', state_id: '28')
    Spree::City.find_or_create_by(id: 426, name: 'Kabupaten Kolaka', state_id: '28')
    Spree::City.find_or_create_by(id: 427, name: 'Kabupaten Konawe Selatan', state_id: '28')
    Spree::City.find_or_create_by(id: 428, name: 'Kabupaten Bombana', state_id: '28')
    Spree::City.find_or_create_by(id: 429, name: 'Kabupaten Wakatobi', state_id: '28')
    Spree::City.find_or_create_by(id: 430, name: 'Kabupaten Kolaka Utara', state_id: '28')
    Spree::City.find_or_create_by(id: 431, name: 'Kabupaten Buton Utara', state_id: '28')
    Spree::City.find_or_create_by(id: 432, name: 'Kabupaten Konawe Utara', state_id: '28')
    Spree::City.find_or_create_by(id: 433, name: 'Kabupaten Kolaka Timur', state_id: '28')
    Spree::City.find_or_create_by(id: 434, name: 'Kabupaten Konawe Kepulauan', state_id: '28')
    Spree::City.find_or_create_by(id: 435, name: 'Kabupaten Muna Barat', state_id: '28')
    Spree::City.find_or_create_by(id: 436, name: 'Kabupaten Buton Tengah', state_id: '28')
    Spree::City.find_or_create_by(id: 437, name: 'Kabupaten Buton Selatan', state_id: '28')
    Spree::City.find_or_create_by(id: 438, name: 'Kota Kendari', state_id: '28')
    Spree::City.find_or_create_by(id: 439, name: 'Kota Baubau', state_id: '28')
    Spree::State.find_or_create_by(id: 29, name: 'Gorontalo', country_id: country.id)
    Spree::City.find_or_create_by(id: 440, name: 'Kabupaten Boalemo', state_id: '29')
    Spree::City.find_or_create_by(id: 441, name: 'Kabupaten Gorontalo', state_id: '29')
    Spree::City.find_or_create_by(id: 442, name: 'Kabupaten Pohuwato', state_id: '29')
    Spree::City.find_or_create_by(id: 443, name: 'Kabupaten Bone Bolango', state_id: '29')
    Spree::City.find_or_create_by(id: 444, name: 'Kabupaten Gorontalo Utara', state_id: '29')
    Spree::City.find_or_create_by(id: 445, name: 'Kota Gorontalo', state_id: '29')
    Spree::State.find_or_create_by(id: 30, name: 'Sulawesi Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 446, name: 'Kabupaten Majene', state_id: '30')
    Spree::City.find_or_create_by(id: 447, name: 'Kabupaten Polewali Mandar', state_id: '30')
    Spree::City.find_or_create_by(id: 448, name: 'Kabupaten Mamasa', state_id: '30')
    Spree::City.find_or_create_by(id: 449, name: 'Kabupaten Mamuju', state_id: '30')
    Spree::City.find_or_create_by(id: 450, name: 'Kabupaten Mamuju Utara', state_id: '30')
    Spree::City.find_or_create_by(id: 451, name: 'Kabupaten Mamuju Tengah', state_id: '30')
    Spree::State.find_or_create_by(id: 31, name: 'Maluku', country_id: country.id)
    Spree::City.find_or_create_by(id: 452, name: 'Kabupaten Maluku Tenggara Barat', state_id: '31')
    Spree::City.find_or_create_by(id: 453, name: 'Kabupaten Maluku Tenggara', state_id: '31')
    Spree::City.find_or_create_by(id: 454, name: 'Kabupaten Maluku Tengah', state_id: '31')
    Spree::City.find_or_create_by(id: 455, name: 'Kabupaten Buru', state_id: '31')
    Spree::City.find_or_create_by(id: 456, name: 'Kabupaten Kepulauan Aru', state_id: '31')
    Spree::City.find_or_create_by(id: 457, name: 'Kabupaten Seram Bagian Barat', state_id: '31')
    Spree::City.find_or_create_by(id: 458, name: 'Kabupaten Seram Bagian Timur', state_id: '31')
    Spree::City.find_or_create_by(id: 459, name: 'Kabupaten Maluku Barat Daya', state_id: '31')
    Spree::City.find_or_create_by(id: 460, name: 'Kabupaten Buru Selatan', state_id: '31')
    Spree::City.find_or_create_by(id: 461, name: 'Kota Ambon', state_id: '31')
    Spree::City.find_or_create_by(id: 462, name: 'Kota Tual', state_id: '31')
    Spree::State.find_or_create_by(id: 32, name: 'Maluku Utara', country_id: country.id)
    Spree::City.find_or_create_by(id: 463, name: 'Kabupaten Halmahera Barat', state_id: '32')
    Spree::City.find_or_create_by(id: 464, name: 'Kabupaten Halmahera Tengah', state_id: '32')
    Spree::City.find_or_create_by(id: 465, name: 'Kabupaten Kepulauan Sula', state_id: '32')
    Spree::City.find_or_create_by(id: 466, name: 'Kabupaten Halmahera Selatan', state_id: '32')
    Spree::City.find_or_create_by(id: 467, name: 'Kabupaten Halmahera Utara', state_id: '32')
    Spree::City.find_or_create_by(id: 468, name: 'Kabupaten Halmahera Timur', state_id: '32')
    Spree::City.find_or_create_by(id: 469, name: 'Kabupaten Pulau Morotai', state_id: '32')
    Spree::City.find_or_create_by(id: 470, name: 'Kabupaten Pulau Taliabu', state_id: '32')
    Spree::City.find_or_create_by(id: 471, name: 'Kota Ternate', state_id: '32')
    Spree::City.find_or_create_by(id: 472, name: 'Kota Tidore Kepulauan', state_id: '32')
    Spree::State.find_or_create_by(id: 33, name: 'Papua Barat', country_id: country.id)
    Spree::City.find_or_create_by(id: 473, name: 'Kabupaten Fakfak', state_id: '33')
    Spree::City.find_or_create_by(id: 474, name: 'Kabupaten Kaimana', state_id: '33')
    Spree::City.find_or_create_by(id: 475, name: 'Kabupaten Teluk Wondama', state_id: '33')
    Spree::City.find_or_create_by(id: 476, name: 'Kabupaten Teluk Bintuni', state_id: '33')
    Spree::City.find_or_create_by(id: 477, name: 'Kabupaten Manokwari', state_id: '33')
    Spree::City.find_or_create_by(id: 478, name: 'Kabupaten Sorong Selatan', state_id: '33')
    Spree::City.find_or_create_by(id: 479, name: 'Kabupaten Sorong', state_id: '33')
    Spree::City.find_or_create_by(id: 480, name: 'Kabupaten Raja Ampat', state_id: '33')
    Spree::City.find_or_create_by(id: 481, name: 'Kabupaten Tambrauw', state_id: '33')
    Spree::City.find_or_create_by(id: 482, name: 'Kabupaten Maybrat', state_id: '33')
    Spree::City.find_or_create_by(id: 483, name: 'Kabupaten Manokwari Selatan', state_id: '33')
    Spree::City.find_or_create_by(id: 484, name: 'Kabupaten Pegunungan Arfak', state_id: '33')
    Spree::City.find_or_create_by(id: 485, name: 'Kota Sorong', state_id: '33')
    Spree::State.find_or_create_by(id: 34, name: 'Papua', country_id: country.id)
    Spree::City.find_or_create_by(id: 486, name: 'Kabupaten Merauke', state_id: '34')
    Spree::City.find_or_create_by(id: 487, name: 'Kabupaten Jayawijaya', state_id: '34')
    Spree::City.find_or_create_by(id: 488, name: 'Kabupaten Jayapura', state_id: '34')
    Spree::City.find_or_create_by(id: 489, name: 'Kabupaten Nabire', state_id: '34')
    Spree::City.find_or_create_by(id: 490, name: 'Kabupaten Kepulauan Yapen', state_id: '34')
    Spree::City.find_or_create_by(id: 491, name: 'Kabupaten Biak Numfor', state_id: '34')
    Spree::City.find_or_create_by(id: 492, name: 'Kabupaten Paniai', state_id: '34')
    Spree::City.find_or_create_by(id: 493, name: 'Kabupaten Puncak Jaya', state_id: '34')
    Spree::City.find_or_create_by(id: 494, name: 'Kabupaten Mimika', state_id: '34')
    Spree::City.find_or_create_by(id: 495, name: 'Kabupaten Boven Digoel', state_id: '34')
    Spree::City.find_or_create_by(id: 496, name: 'Kabupaten Mappi', state_id: '34')
    Spree::City.find_or_create_by(id: 497, name: 'Kabupaten Asmat', state_id: '34')
    Spree::City.find_or_create_by(id: 498, name: 'Kabupaten Yahukimo', state_id: '34')
    Spree::City.find_or_create_by(id: 499, name: 'Kabupaten Pegunungan Bintang', state_id: '34')
    Spree::City.find_or_create_by(id: 500, name: 'Kabupaten Tolikara', state_id: '34')
    Spree::City.find_or_create_by(id: 501, name: 'Kabupaten Sarmi', state_id: '34')
    Spree::City.find_or_create_by(id: 502, name: 'Kabupaten Keerom', state_id: '34')
    Spree::City.find_or_create_by(id: 503, name: 'Kabupaten Waropen', state_id: '34')
    Spree::City.find_or_create_by(id: 504, name: 'Kabupaten Supiori', state_id: '34')
    Spree::City.find_or_create_by(id: 505, name: 'Kabupaten Mamberamo Raya', state_id: '34')
    Spree::City.find_or_create_by(id: 506, name: 'Kabupaten Nduga', state_id: '34')
    Spree::City.find_or_create_by(id: 507, name: 'Kabupaten Lanny Jaya', state_id: '34')
    Spree::City.find_or_create_by(id: 508, name: 'Kabupaten Mamberamo Tengah', state_id: '34')
    Spree::City.find_or_create_by(id: 509, name: 'Kabupaten Yalimo', state_id: '34')
    Spree::City.find_or_create_by(id: 510, name: 'Kabupaten Puncak', state_id: '34')
    Spree::City.find_or_create_by(id: 511, name: 'Kabupaten Dogiyai', state_id: '34')
    Spree::City.find_or_create_by(id: 512, name: 'Kabupaten Intan Jaya', state_id: '34')
    Spree::City.find_or_create_by(id: 513, name: 'Kabupaten Deiyai', state_id: '34')
    Spree::City.find_or_create_by(id: 514, name: 'Kota Jayapura', state_id: '34')
  end
end
